/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyGantt {
        "gZoomIn": () => Promise<void>;
        "gZoomOut": () => Promise<void>;
        /**
          * The task data
         */
        "taskdata": {};
        "updateCriticalPath": (toggle: any) => Promise<void>;
    }
}
declare global {
    interface HTMLMyGanttElement extends Components.MyGantt, HTMLStencilElement {
    }
    var HTMLMyGanttElement: {
        prototype: HTMLMyGanttElement;
        new (): HTMLMyGanttElement;
    };
    interface HTMLElementTagNameMap {
        "my-gantt": HTMLMyGanttElement;
    }
}
declare namespace LocalJSX {
    interface MyGantt {
        /**
          * The task data
         */
        "taskdata"?: {};
    }
    interface IntrinsicElements {
        "my-gantt": MyGantt;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-gantt": LocalJSX.MyGantt & JSXBase.HTMLAttributes<HTMLMyGanttElement>;
        }
    }
}
